[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "nifi-monitor"
version = "0.1.0"

[tool.setuptools]
packages = [
  "lib",
  "analysis",
  "config",
  "information"
]

